version: "3"
services:
  app:
    build:
      context: .
      args:
        VARIANT: "14"
    command: sleep infinity
    volumes:
      - ../:/workspace
      - node_modules:/workspace/node_modules
    tty: true
volumes:
  node_modules:
